[name: publish
on: [push]
jobs:
       publish-hello-docker-image:
       runs-on: ubuntu-latest
       steps:
              - uses: actions/checkout@v2
              - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                     registry: ghcr.io
                     username: ${{ github.actor }}
                     password: ${{ secrets.M2_LEAD_TECH }}
              - name: Build the hello-docker Docker image
              run: |
                     docker build . --tag ghcr.io/RomainLENTZ/hello-docker-gcr-demo:staging
                     docker run ghcr.io/RomainLENTZ/hello-docker-gcr-demo:staging
                     docker push ghcr.io/RomainLENTZ/hello-docker-gcr-demo:staging]