name: publish
on: [push]
jobs:
       publish-hello-docker-image:
              runs-on: ubuntu-latest
              steps:
                     - uses: actions/checkout@v2
                     - run: npm ci
                     - run: npm run build --if-present
                     - run: npm test
                     - name: Login to GitHub Container Registry
                       uses: docker/login-action@v1
                       with:
                              registry: ghcr.io
                              username: ${{ github.actor }}
                              password: ${{ secrets.M2_LEAD_TECH }}
                     - name: Build the hello-docker Docker image
                       run: |
                              docker build . --tag ghcr.io/romainlentz/m2_lead_tech:staging
                              docker push ghcr.io/romainlentz/m2_lead_tech:staging
                     - name: Coveralls
                       uses: coverallsapp/github-action@v2

